package com.github.taffy128s.tlcdbms;

public enum State {
    START,
    ERROR,
    CREATE_PARSED,
    CREATE_TABLE_PARSED,
    CREATE_TABLE_NAME_PARSED,
    CREATE_TABLE_LEFT_PARSED,
    CREATE_TABLE_CONTENT_NAME_PARSED,
    CREATE_TABLE_CONTENT_INT_PARSED,
    CREATE_TABLE_CONTENT_CHAR_PARSED,
    CREATE_TABLE_CONTENT_CHAR_LEFT_PARSED,
    CREATE_TABLE_CONTENT_CHAR_NUM_PARSED,
    CREATE_TABLE_CONTENT_CHAR_RIGHT_PARSED,
    CREATE_TABLE_CONTENT_PRIMARY_PARSED,
    CREATE_TABLE_CONTENT_PRIMARY_KEY_PARSED,
    CREATE_TABLE_RIGHT_PARSED
}
